[package]
name = "audio-navigation-tts"
version = "0.1.0"
edition = "2021"

[dependencies]
espeakng-sys = { git = "https://github.com/emassey0135/espeakng-sys.git", version = "0.3.0", features = ["clang-runtime"] }
jni = "0.21.1"
lazy_static = "1.5.0"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
build-target = "0.4.0"
