name: build
on: [pull_request, push]
jobs:
  build:
    name: Build - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            output-file: libaudio_navigation_tts.so
          - os-name: Linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            output-file: libaudio_navigation_tts.so
          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            output-file: audio_navigation_tts.dll
          - os-name: Windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
            output-file: audio_navigation_tts.dll
          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
            output-file: libaudio_navigation_tts.dylib
          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
            output-file: libaudio_navigation_tts.dylib
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.os-name }}
          path: targets/release/${{ matrix.platform.output-file }}
